variable "aws_region" {}
variable "vpc_cidr" {}
variable "web_subnets_cidr" {}
variable "app_subnets_cidr" {}
variable "db_subnets_cidr" {}
variable "reserved_subnets_cidr" {}
variable "key_name" {}
variable "public_key_path" {}
variable "instance_type" {}